apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: roboshop  # Set the namespace to "roboshop"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-pvc-volume
              mountPath: /usr/share/nginx/html  # Mount the PVC to the Nginx default web root
      volumes:
        - name: my-pvc-volume
          persistentVolumeClaim:
            claimName: my-pvc-new
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-new  # Give it a new name to avoid conflicts
  namespace: roboshop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 3Gi  # Set the desired storage size

