apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cart
      tier: app
  template:
    metadata:
      labels:
        name: cart
        tier: app
    spec:
      containers:
        - name: cart
          imagePullPolicy: Always
          image: pavanreddy1219/cart:k8
          env:
            - name: CATALOGUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: cart-config
                  key: CATALOGUE_HOST
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: cart-config
                  key: REDIS_HOST
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  CATALOGUE_HOST: "catalogue"
  REDIS_HOST: "redis"

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    tier: app
    name: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
