apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
      name: ratings
  template:
    metadata:
      labels:
        tier: app
        name: ratings
    spec:
      containers:
        - name: rating
          imagePullPolicy: Always
          image: pavanreddy1219/ratings:k8
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    tier: app
    name: ratings
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
