apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  clusterIP: None # headless service
  selector:
    name: mongodb
    tier: db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
      tier: db
  template:
    metadata:
      labels:
        name: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: pavanreddy1219/mongodb:v1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  namespace: roboshop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-sc"
  resources:
    requests:
      storage: 1Gi
